name: Build and Create Executable Artifact

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: kurocha/setup-cpp@v1
        with:
          compiler: 'gcc'

      - name: change into the CD directory
        run: cd CD

      - name: Build 
        run: g++ -std=c++17 src/main.cpp src/cd.cpp -o cd.exe


      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: cd-executable
          path: cd

