name: Build and Create Executable Artifact

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: kurocha/setup-cpp@v1
        with:
          compiler: 'gcc'

      - name: Build MFRT
        run: g++ MFRT/mfrt.cpp -o MFRT/mfrt -std=c++11 -lstdc++

      - name: Build Kohnert CD
        run: (cd CD_Kohnert && make)

      - name: Build Pokor CD
        run: (cd CD_Pokor && make)

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: cd-executable
          path: CD_Kohnert/cd

   
